<?php

namespace Vartruexuan\HyperfExcel\Listener;

use Psr\Container\ContainerInterface;
use Vartruexuan\HyperfExcel\Event\AfterExport;
use Vartruexuan\HyperfExcel\Event\AfterExportData;
use Vartruexuan\HyperfExcel\Event\AfterExportSheet;
use Vartruexuan\HyperfExcel\Event\AfterImport;
use Vartruexuan\HyperfExcel\Event\AfterImportData;
use Vartruexuan\HyperfExcel\Event\AfterImportSheet;
use Vartruexuan\HyperfExcel\Event\BeforeExport;
use Vartruexuan\HyperfExcel\Event\BeforeExportData;
use Vartruexuan\HyperfExcel\Event\BeforeExportSheet;
use Vartruexuan\HyperfExcel\Event\BeforeImport;
use Vartruexuan\HyperfExcel\Event\BeforeImportSheet;
use Vartruexuan\HyperfExcel\Event\Error;
use Vartruexuan\HyperfExcel\Event\Event;
use Vartruexuan\HyperfExcel\Logger\ExcelLoggerInterface;
use Vartruexuan\HyperfExcel\Progress\ProgressData;
use Vartruexuan\HyperfExcel\Progress\ProgressInterface;

class ProgressListener extends BaseListener
{
    protected ProgressInterface $progress;

    public function __construct(ContainerInterface $container, ExcelLoggerInterface $excelLogger, ProgressInterface $progress)
    {
        parent::__construct($container, $excelLogger);

        $this->progress = $progress;
    }

    public function process(object $event): void
    {
        /**
         * @var Event $event
         */
        $enable = $this->progress->getConfig()['progress']['enable'] ?? true;
        if (!$enable || !$event->config->getIsProgress()) {
            return;
        }
        parent::process($event); // TODO: Change the autogenerated stub
    }

    function beforeExport(object $event)
    {
        /**
         * @var BeforeExport $event
         */
        $this->progress->initRecord($event->config);
    }

    function beforeExportExcel(object $event)
    {
        // TODO: Implement beforeExportExcel() method.
    }

    function beforeExportData(object $event)
    {
        /**
         * @var BeforeExportData $event
         */
        $this->progress->setSheetProgress($event->config, $event->exportCallbackParam->sheet->name, new ProgressData([
            'total' => $event->exportCallbackParam->totalCount,
            'status' => ProgressData::PROGRESS_STATUS_PROCESS,
        ]));
    }

    function beforeExportSheet(object $event)
    {
        /**
         * @var BeforeExportSheet $event
         */
        $this->progress->setSheetProgress($event->config, $event->sheet->name, new ProgressData([
            'status' => ProgressData::PROGRESS_STATUS_PROCESS,
        ]));
    }

    function afterExport(object $event)
    {
        /**
         * @var AfterExport $event
         */
        $record = $this->progress->getRecord($event->config);

        $status = !in_array($record->progress->status, [ProgressData::PROGRESS_STATUS_END, ProgressData::PROGRESS_STATUS_FAIL]) ? ProgressData::PROGRESS_STATUS_END : $record->progress->status;
        $data = $event->data ?: $record->data;
        $this->progress->setProgress($event->config, new ProgressData([
            'status' => $status,
        ]), $data);
    }

    function afterExportData(object $event)
    {
        /**
         * @var AfterExportData $event
         */
        $success = count($event->data ?? []);
        $this->progress->setSheetProgress($event->config, $event->exportCallbackParam->sheet->name, new ProgressData([
            'status' => ProgressData::PROGRESS_STATUS_PROCESS,
            'success' => $success,
            'progress' => $success,
        ]));
    }

    function afterExportExcel(object $event)
    {

        // TODO: Implement afterExportExcel() method.
    }

    function afterExportSheet(object $event)
    {
        /**
         * @var AfterExportSheet $event
         */
        $this->progress->setSheetProgress($event->config, $event->sheet->name, new ProgressData([
            'status' => ProgressData::PROGRESS_STATUS_END,
        ]));
    }


    function beforeImport(object $event)
    {
        /**
         * @var BeforeImport $event
         */
        $this->progress->initRecord($event->config);
    }

    function beforeImportExcel(object $event)
    {
        // TODO: Implement beforeImportExcel() method.
    }

    function beforeImportData(object $event)
    {
        // TODO: Implement beforeImportData() method.
    }

    function beforeImportSheet(object $event)
    {
        /**
         * @var BeforeImportSheet $event
         */
        $this->progress->setSheetProgress($event->config, $event->sheet->name, new ProgressData([
            'status' => ProgressData::PROGRESS_STATUS_PROCESS,
        ]));
    }

    function afterImport(object $event)
    {
        /**
         * @var AfterImport $event
         */
        $record = $this->progress->getRecord($event->config);

        $status = !in_array($record->progress->status, [ProgressData::PROGRESS_STATUS_END, ProgressData::PROGRESS_STATUS_FAIL]) ? ProgressData::PROGRESS_STATUS_END : $record->progress->status;
        $data = $event->data ?: $record->data;
        $this->progress->setProgress($event->config, new ProgressData([
            'status' => $status,
        ]), $data);
    }

    function afterImportData(object $event)
    {
        /**
         * @var AfterImportData $event
         */
        $this->progress->setSheetProgress($event->config, $event->importCallbackParam->sheet->name, new ProgressData([
            'status' => ProgressData::PROGRESS_STATUS_PROCESS,
            'progress' => 1,
            'success' => $event->exception ? 0 : 1,
            'fail' => $event->exception ? 1 : 0,

        ]));
        if ($event->exception) {
            $this->progress->pushMessage($event->config->getToken(), $event->exception->getMessage());
        }
    }

    function afterImportExcel(object $event)
    {
        // TODO: Implement afterImportExcel() method.
    }

    function afterImportSheet(object $event)
    {
        /**
         * @var AfterImportSheet $event
         */
        $record = $this->progress->getRecord($event->config);
        $this->progress->setSheetProgress($event->config, $event->sheet->name, new ProgressData([
            'status' => ProgressData::PROGRESS_STATUS_END,
            'total' => $record->sheetListProgress[$event->sheet->name]?->progress,
        ]));
    }

    function error(object $event)
    {
        /**
         * @var Error $event
         */
        $this->progress->setProgress($event->config, new ProgressData([
            'status' => ProgressData::PROGRESS_STATUS_FAIL,
        ]));
        $this->progress->pushMessage($event->config->getToken(), $event->exception->getMessage());
    }
}